### ISSUE TITLE
Url to media

### ISSUE THREAD

**Issue by wvdvegt** [codeodor/upnplib-mediaserver-wrapper#1]
Hi,

Can you tell me how to obtain the url to a videom image or music item using your wrapper?

Enumerating the DLNA folder structure I managed to get working in my application. I need the url to ChromeCast it.

**Comment by codeodor** [comment]
It's been a LONG time since I looked at this, so I apologize if I'm wrong, but I did try to familiarize myself with it briefly before answering.

It looks like this was just a wrapper around the UPNPLib that is included in, maybe the .NET framework, or some other COM service that runs on Windows.

So this wrapper doesn't expose it directly, but given that it gives you directories and a list of their contents, my guess is that if you were to inspect one of the children in the directory, there's a method included in UPNPLib that would get its URL.

I'm not sure what that would be though, without trying to read through all the documentation. But I'm not even sure whether that project still exists, or looks remotely similar to what it did when I wrote this. 

It's been a while! 😄 

I hope that at least gets you going in the right direction. Good luck!
